[package]
name = "support"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
atty = "0.2"
bytes = "1.11.1"
futures = { version = "0.3", default-features = false }
header-plz = { git = "ssh://git@github.com/caido/primitives.git", rev = "b24d61a8602d3dc19881641dd527ee727b6908ac" }
http-plz = { git = "ssh://git@github.com/caido/http-plz.git", rev = "4bb74a150b5d17f9a05ed6550e25257411bd15ba" }
tokio = { version = "1", features = ["time"] }
tokio-test = "0.4"
tracing = "0.1"
tracing-subscriber = { version = "0.3", default-features = false, features = ["fmt"] }
tracing-tree = "0.4.1"
two-plz = { path = "../..", features = ["stream", "unstable"] }
